2424

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -45,9 +45,11 @@ jobs:
             fi
           done
 
-      - name: Vérifier que l'application répond
-        run: |
-          curl --fail http://localhost:8080 || (echo "L'application ne répond pas" && exit 1)
+   #   - name: Vérifier que l'application répond
+    #    run: |
+     #     curl --fail http://localhost:8080 || (echo "L'application ne répond pas" && exit 1)
+
+
 
       - name: Stop container
         run: docker stop superbowl-int
